export const ON_ADD_IN_BASKET_BTN_CLICK = 'ON_ADD_IN_BASKET_BTN_CLICK'
export const ON_LANG_BTN_CLICK = 'ON_RU_BTN_CLICK'
export const ON_SUBMIT_FORM = 'ON_SUBMIT_FORM'
export const ON_ADD_DEL_COUNT_PRODUCT_BTN = 'ON_ADD_DEL_COUNT_PRODUCT_BTN'
export const ON_PRODUCT_COUNT_ZERO = 'ON_PRODUCT_COUNT_ZERO'
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'





